//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AcquisitionEvent
    {
        public AcquisitionEvent()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> VendorID { get; set; }
        [Display(Name = "Amount Paid")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> AmtPaid { get; set; }
        public string Description { get; set; }
        public string Justification { get; set; }
        public Nullable<int> DeliveryID { get; set; }
    
        public virtual DeliveryReceived DeliveryReceived { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
