//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ContactInformation
    {
        public ContactInformation()
        {
            this.AccountContacts = new HashSet<AccountContact>();
            this.Accounts = new HashSet<Account>();
            this.Employees = new HashSet<Employee>();
            this.InternetDomains = new HashSet<InternetDomain>();
            this.MOUs = new HashSet<MOU>();
            this.QueryEvents = new HashSet<QueryEvent>();
            this.Vendors = new HashSet<Vendor>();
            this.VendorContacts = new HashSet<VendorContact>();
        }
    
        public int Id { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone 1")]
        public string Phone1 { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone 2")]
        public string Phone2 { get; set; }
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email 1")]
        public string Email1 { get; set; }
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email 2")]
        public string Email2 { get; set; }
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email 3")]
        public string Email3 { get; set; }
        [Display(Name = "Address 1")]
        public string Address1 { get; set; }
        [Display(Name = "City 1")]
        public string City1 { get; set; }
        [Display(Name = "State 1")]
        public string State1 { get; set; }
        [Display(Name = "Zip 1")]
        public string Zip1 { get; set; }
        [Display(Name = "Address 2")]
        public string Address2 { get; set; }
        [Display(Name = "City 2")]
        public string City2 { get; set; }
        [Display(Name = "State 2")]
        public string State2 { get; set; }
        [Display(Name = "Zip 2")]
        public string Zip2 { get; set; }
        public string Description { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone 3")]
        public string Phone3 { get; set; }
    
        public virtual ICollection<AccountContact> AccountContacts { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<InternetDomain> InternetDomains { get; set; }
        public virtual ICollection<MOU> MOUs { get; set; }
        public virtual ICollection<QueryEvent> QueryEvents { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
        public virtual ICollection<VendorContact> VendorContacts { get; set; }
    }
}
