//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryReceived
    {
        public DeliveryReceived()
        {
            this.AcquisitionEvents = new HashSet<AcquisitionEvent>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<int> EmployeeOrderedID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<int> EmployeeReceivingID { get; set; }
    
        public virtual ICollection<AcquisitionEvent> AcquisitionEvents { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
