//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetDomain
    {
        public int Id { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Registrant { get; set; }
        public string DomainName { get; set; }
        public string RegistrarName { get; set; }
        public string RegistrarHomepage { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string AdministrativeContactName { get; set; }
        public Nullable<int> AdministrativeContactInformationID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ContactInformation ContactInformation { get; set; }
    }
}
