//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PaymentReceived
    {
        public int Id { get; set; }
        public Nullable<int> AccountID { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<decimal> Amount { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
