//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Procedure
    {
        public Procedure()
        {
            this.SupportEvents = new HashSet<SupportEvent>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Procedure")]
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Text { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Modified")]
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SupportEvent> SupportEvents { get; set; }
    }
}
