//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Project
    {
        public Project()
        {
            this.Invoices = new HashSet<Invoice>();
            this.ProjectEvents = new HashSet<ProjectEvent>();
        }
    
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Start")]
        public Nullable<System.DateTime> DateStart { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Complete")]
        public Nullable<System.DateTime> DateComplete { get; set; }
        public string Description { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ProjectEvent> ProjectEvents { get; set; }
        public virtual ProjectType ProjectType { get; set; }
    }
}
