//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Protocol
    {
        public Protocol()
        {
            this.VPNs = new HashSet<VPN>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Protocol")]
        public string Protocol1 { get; set; }
    
        public virtual ICollection<VPN> VPNs { get; set; }
    }
}
