//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryEvent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ContactInformationID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual ContactInformation ContactInformation { get; set; }
        public virtual QueryStatu QueryStatu { get; set; }
        public virtual QueryType QueryType { get; set; }
    }
}
