//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Invoices = new HashSet<Invoice>();
            this.SupportEvents = new HashSet<SupportEvent>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOpened { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateClosed { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public Nullable<int> PriorityID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual ICollection<SupportEvent> SupportEvents { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
    }
}
