//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class VPN
    {
        public int Id { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ClassID { get; set; }
        [Display(Name = "IP Address")]
        public string IPAddress { get; set; }
        [Display(Name = "Virtual IP Range")]
        public string VirtualIPRange { get; set; }
        [Display(Name = "Allowed LAN Access")]
        public string AllowedLANAccess { get; set; }
        public string Name { get; set; }
        [Display(Name = "Needed By")]
        public string NeededBy { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> ProtocolID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Protocol Protocol { get; set; }
        public virtual VPNClass VPNClass { get; set; }
    }
}
