//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPNClass
    {
        public VPNClass()
        {
            this.VPNs = new HashSet<VPN>();
        }
    
        public int Id { get; set; }
        public string Class { get; set; }
    
        public virtual ICollection<VPN> VPNs { get; set; }
    }
}
