//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwdapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WhiteWaveDBEntities : DbContext
    {
        public WhiteWaveDBEntities()
            : base("name=WhiteWaveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountContact> AccountContacts { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<AcquisitionEvent> AcquisitionEvents { get; set; }
        public virtual DbSet<BankDeposit> BankDeposits { get; set; }
        public virtual DbSet<CLOU> CLOUs { get; set; }
        public virtual DbSet<ContactInformation> ContactInformations { get; set; }
        public virtual DbSet<DeliveryMade> DeliveryMades { get; set; }
        public virtual DbSet<DeliveryReceived> DeliveryReceiveds { get; set; }
        public virtual DbSet<EmailAddress> EmailAddresses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<ExpenditureEvent> ExpenditureEvents { get; set; }
        public virtual DbSet<InternetDomain> InternetDomains { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<IPAddress> IPAddresses { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemStatu> ItemStatus { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<MOU> MOUs { get; set; }
        public virtual DbSet<PaymentReceived> PaymentReceiveds { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<ProjectEvent> ProjectEvents { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<Protocol> Protocols { get; set; }
        public virtual DbSet<QueryEvent> QueryEvents { get; set; }
        public virtual DbSet<QueryStatu> QueryStatus { get; set; }
        public virtual DbSet<QueryType> QueryTypes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<SoftwareInstallation> SoftwareInstallations { get; set; }
        public virtual DbSet<SupportAgreement> SupportAgreements { get; set; }
        public virtual DbSet<SupportEvent> SupportEvents { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketStatu> TicketStatus { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorContact> VendorContacts { get; set; }
        public virtual DbSet<VendorStatu> VendorStatus { get; set; }
        public virtual DbSet<VPNClass> VPNClasses { get; set; }
        public virtual DbSet<VPN> VPNs { get; set; }
    }
}
